
 ____       ____       ____       ____
/    \     /    \     /    \     /    \
|  #################################  |
\__#_/     \____/     \____/     \_#__/
   #    _        _______  _____    #
   #   (_)      |_   __ \|_   _|   #      -*-     v 3.0.0-beta  -*-
   #   __  ______ | |__) | | |     #
   Y  [  ||______||  ___/  | |     #      A Universal Force Engine
  0 0  | |       _| |_    _| |_    #
   #  [___]     |_____|  |_____|   #
 __#_       ____       ____       _#__
/  # \     /    \     /    \     / #  \
|  #################################  |
\____/     \____/     \____/     \____/

    
<ipi.inputs.motion.dynamics.InputDynamics object at 0x7fcbd8ea6450>
 # Initializing system object 
 # Initializing simulation object 
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Resampling velocities at temperature 300.0 kelvin
 # Binding the forces 
Traceback (most recent call last):
  File "/home/ak2921/i-pi/ipi/interfaces/sockets.py", line 655, in open
    self.server.bind(self.sockets_prefix + self.address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ak2921/i-pi/bin/i-pi", line 115, in <module>
    main(args[0], options)
  File "/home/ak2921/i-pi/bin/i-pi", line 61, in main
    simulation = Simulation.load_from_xml(fn_input, request_banner=True, custom_verbosity=options.verbosity, sockets_prefix=options.sockets_prefix)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ak2921/i-pi/ipi/engine/simulation.py", line 107, in load_from_xml
    simulation.bind(read_only)
  File "/home/ak2921/i-pi/ipi/engine/simulation.py", line 216, in bind
    f.start()
  File "/home/ak2921/i-pi/ipi/engine/forcefields.py", line 352, in start
    self.socket.open()
  File "/home/ak2921/i-pi/ipi/interfaces/sockets.py", line 660, in open
    raise RuntimeError(
RuntimeError: Error opening unix socket. Check if a file /tmp/ipi_driver exists, and remove it if unused.
